import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'post_login_req.mapper.dart';

@MappableClass()
class PostLoginReq with PostLoginReqMappable {
  final String email;
  final String password;

  PostLoginReq({required this.email, required this.password});
}
