name: atlas_web
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  file_picker: ^6.1.1
  loading_animation_widget: ^1.2.0+4
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  equatable: ^2.0.5
  dart_mappable: ^4.0.1
  injectable: ^2.3.2
  get_it: ^7.6.4
  dio: ^5.4.0
  go_router: ^12.1.1
  adaptive_breakpoints: ^0.1.1
  dual_screen: ^1.0.4
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.4
  images_picker: ^1.2.11
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.1
  intl: ^0.18.1




  #Firebase_Related
  firebase_core: ^2.21.0
  firebase_storage: ^11.0.6
  cloud_firestore: ^4.13.1
  firebase_database: ^10.0.8
  firebase_auth: ^4.1.4
  cloud_functions: ^4.0.13


  #Bloc
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  flip_card: ^0.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.6
  dart_mappable_builder: ^4.0.1


flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/icon/
   - assets/images/
   - assets/languages/

