// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWv_2JfojQvlbmCie1Iocm2bRHSzyatlA',
    appId: '1:133923101989:web:53ffa9c0ef4ef7728c4ecc',
    messagingSenderId: '133923101989',
    projectId: 'atlas-7f720',
    authDomain: 'atlas-7f720.firebaseapp.com',
    storageBucket: 'atlas-7f720.appspot.com',
    measurementId: 'G-W4Z40M9F4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQff8TUP9qW1WJ1LGK_enItjLteDP3mos',
    appId: '1:133923101989:android:da5966be9a649d038c4ecc',
    messagingSenderId: '133923101989',
    projectId: 'atlas-7f720',
    storageBucket: 'atlas-7f720.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl1zNLaYU4gl4sX5CCmGCHrdI1y3HuH2E',
    appId: '1:133923101989:ios:ab15596dfde2a3188c4ecc',
    messagingSenderId: '133923101989',
    projectId: 'atlas-7f720',
    storageBucket: 'atlas-7f720.appspot.com',
    iosBundleId: 'com.atlas.atlasWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl1zNLaYU4gl4sX5CCmGCHrdI1y3HuH2E',
    appId: '1:133923101989:ios:f180617a8768d8ea8c4ecc',
    messagingSenderId: '133923101989',
    projectId: 'atlas-7f720',
    storageBucket: 'atlas-7f720.appspot.com',
    iosBundleId: 'com.atlas.atlasWeb.RunnerTests',
  );
}
