// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdq60Crgnilpkb6W9-68PNCXff41-7dBU',
    appId: '1:730810421289:web:de557de44efd400631cc38',
    messagingSenderId: '730810421289',
    projectId: 'project-14b44',
    authDomain: 'project-14b44.firebaseapp.com',
    storageBucket: 'project-14b44.appspot.com',
    measurementId: 'G-R5LMCLNYS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-45bfPQ-j45rzoqswhIm26qVx2vbdZ8E',
    appId: '1:730810421289:android:e704b44ddd49af2931cc38',
    messagingSenderId: '730810421289',
    projectId: 'project-14b44',
    storageBucket: 'project-14b44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMCV5vJztsyg5z0vj-y4SDjyXCib3DQAw',
    appId: '1:730810421289:ios:7e3f8c3da8f36a1b31cc38',
    messagingSenderId: '730810421289',
    projectId: 'project-14b44',
    storageBucket: 'project-14b44.appspot.com',
    iosBundleId: 'com.atlas.atlas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMCV5vJztsyg5z0vj-y4SDjyXCib3DQAw',
    appId: '1:730810421289:ios:5f9cbef303cb2f9831cc38',
    messagingSenderId: '730810421289',
    projectId: 'project-14b44',
    storageBucket: 'project-14b44.appspot.com',
    iosBundleId: 'com.atlas.atlas.RunnerTests',
  );
}
